[package]
name = "rt-logger"
version = "0.1.0"
authors = ["Hadrien Grasland <grasland@lal.in2p3.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
abomonation = { path = "../abomonation" }